apiVersion: wac-fiit.github.io/v1alpha1
kind: Project
metadata:
  name: orp-or-planner
spec:
  title: "Plánovanie využitia operačných sál"
  description: "Plánovanie operácií, správa pacientov, sál a zdravotníckeho personálu."
  authors: "Filip Chromek, Dominik Mojto"
  azureLink: "or-planner-wac.westeurope.cloudapp.azure.com/fea/orp-or-planner"
  frontendRepoUrl: "https://github.com/FilipChromek/operation-planner-ufe"
  backendRepoUrl: "https://github.com/FilipChromek/operation-planner-webapi"
  gitopsRepoUrl: "https://github.com/FilipChromek/operation-planner-gitops"
