apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wac-hospital

labels:
  - pairs:
      app.kubernetes.io/part-of: wac-hospital
      wac-fiit.github.io/project: orp-or-planner

resources:
  - ../../../apps/orp-or-planner-ufe
  - ../../../apps/orp-or-planner-webapi

components:
  - ../../../components/mongodb
  - ../../../components/version-developers
